import slide1Image from '../public/images/slide-1.jpg'
import carImage from '../public/images/car.png'
import onlineBookingImage from '../public/images/online-booking.png'
import presenceBgImage from '../public/images/presence-bg.jpg'
import locationDubaiImage from '../public/images/location-dubai.png'
import loanCalculatorImage from '../public/images/loan-calculator.png'
import loginBg from '../public/images/login-bg.png'
import featureIcon from '../public/icons/feature-icon.png'
import carConditionImage from '../public/images/car-condition.png'
import bannerLoanImage from '../public/images/banner-loan.png'
import buycarCheckoutImage from '../public/images/buycar-checkout-img.png'
import hiredriverBgImage from '../public/images/hire-driver-bg-img.png'
import hireDriveAboutusImg from '../public/images/aboutus-hiredriver-img.jpg'
import sellcarBgImage from '../public/images/sellcar-bg.jpg'
import rentCarBgImage from '../public/images/rent-car-bg-image.jpg'
import garageBookingImage from '../public/images/garagebookingbg.jpg'
import rentCarLimousineImage from '../public/images/rentcar-limousine-bg.jpg'

export {slide1Image, carImage, onlineBookingImage, presenceBgImage, locationDubaiImage, loanCalculatorImage, loginBg, featureIcon, carConditionImage, bannerLoanImage, buycarCheckoutImage, hiredriverBgImage, hireDriveAboutusImg, sellcarBgImage, rentCarBgImage, garageBookingImage, rentCarLimousineImage}